### ISSUE TITLE
How to make a cooldown for command in custom commands yml in DiscordEconomyBridge?

### ISSUE THREAD

**Issue by Zombix3000** [Pliexe/DiscordEconomyBridge#6]
Hello!
I have a problem with discord economy bridge.
How to make cooldown for command in custom_commands.yml.
Please help me!
[custom_commands.yml.txt](https://github.com/Pliexe/DiscordEconomyBridge/files/12064837/custom_commands.yml.txt)

**Comment by Pliexe** [comment]
Cooldowns would be added the same way they are for normal commands, since custom commands are in a shared space with built-in commands.
So where in config.yml you have for example
```
# Cooldown settings
cooldowns:
  blackjack: 300
  coinflip: 300
  rockpaperscissors: 300
```
You could add
```
# Cooldown settings
cooldowns:
  blackjack: 300
  coinflip: 300
  rockpaperscissors: 300
  work: 250
  nameofmycommand: thetimeofmycooldowninseconds
```
